version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: zprofessors
    restart: always
    ports:
      - "3308:3306/tcp"
      - "33062:33060"
    environment:
      MYSQL_ROOT_PASSWORD: paswrd
      MYSQL_DATABASE: webdb
      MYSQL_USER: medzit
      MYSQL_PASSWORD: paswrd2
    networks:
      - zstudentsntw
  
networks:
  zstudentsntw:
    driver: bridge